//
//  MoviesViewController.swift
//  DevTestArcTouch
//
//  Created by Rafael Zilião on 03/08/2018.
//  Copyright (c) 2018 Rafael Zilião. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MoviesDisplayLogic: class {
    func displaySomething(viewModel: Movies.Something.ViewModel)
    func displayMovies(viewModel: Movies.FetchMovies.ViewModel)
}

class MoviesViewController: UIViewController, MoviesDisplayLogic {
    var interactor: MoviesBusinessLogic?
    var router: (NSObjectProtocol & MoviesRoutingLogic & MoviesDataPassing)?

    // MARK: Object lifecycle
  
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
  
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
  
    // MARK: Setup
  
    private func setup() {
        let viewController = self
        let interactor = MoviesInteractor()
        let presenter = MoviesPresenter()
        let router = MoviesRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
  
    // MARK: Routing
  
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
  
    // MARK: View lifecycle
  
    override func viewDidLoad() {
        super.viewDidLoad()
        doSomething()
        self.moviesTableView.delegate = self
        self.moviesTableView.dataSource = self
        
        self.fetchMovies()
    }
  
    // MARK: Do something
  
    //@IBOutlet weak var nameTextField: UITextField!
    @IBOutlet var moviesTableView: UITableView!
    var movies: [Movie] = []
    
    func doSomething() {
        let request = Movies.Something.Request()
        interactor?.doSomething(request: request)
    }
    
    func fetchMovies() {
        let request = Movies.FetchMovies.Request(page: 1)
        self.interactor?.fetchMovies(request: request)
    }
  
    func displaySomething(viewModel: Movies.Something.ViewModel) {
        //nameTextField.text = viewModel.name
    }
    
    func displayMovies(viewModel: Movies.FetchMovies.ViewModel) {
        self.movies = viewModel.movieResults.movies
        self.moviesTableView.reloadData()
    }
}

extension MoviesViewController: UITableViewDataSource, UITableViewDelegate {
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return self.movies.count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        if let cell = moviesTableView.dequeueReusableCell(withIdentifier: MovieListCell.identifier, for: indexPath) as? MovieListCell {
            
            cell.render(movie: self.movies[indexPath.row])
            
            return cell
        }
        else {
            return UITableViewCell()
        }

    }
    
}
