//
//  MoviesRouter.swift
//  DevTestArcTouch
//
//  Created by Rafael Zilião on 03/08/2018.
//  Copyright (c) 2018 Rafael Zilião. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol MoviesRoutingLogic {
    func routeToMovieDetails(segue: UIStoryboardSegue?)
}

protocol MoviesDataPassing {
    var dataStore: MoviesDataStore? { get }
}

class MoviesRouter: NSObject, MoviesRoutingLogic, MoviesDataPassing {
    weak var viewController: MoviesViewController?
    var dataStore: MoviesDataStore?
  
    // MARK: Routing
  
    func routeToMovieDetails(segue: UIStoryboardSegue?) {
        if let segue = segue {
            let destinationVC = segue.destination as! MovieDetailViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToMovieDetails(source: dataStore!, destination: &destinationDS)
        } else {
            let storyboard = UIStoryboard(name: "Main", bundle: nil)
            let destinationVC = storyboard.instantiateViewController(withIdentifier: "MovieDetailViewController") as! MovieDetailViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToMovieDetails(source: dataStore!, destination: &destinationDS)
            navigateToMovieDetails(source: viewController!, destination: destinationVC)
        }
        }

     //MARK: Navigation
  
    func navigateToMovieDetails(source: MoviesViewController, destination: MovieDetailViewController) {
        source.show(destination, sender: nil)
    }
  
     //MARK: Passing data
  
    func passDataToMovieDetails(source: MoviesDataStore, destination: inout MovieDetailDataStore) {
        destination.movie = source.movie
    }
}
