//
//  MoviesPresenter.swift
//  DevTestArcTouch
//
//  Created by Rafael Zilião on 03/08/2018.
//  Copyright (c) 2018 Rafael Zilião. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MoviesPresentationLogic {
    func presentSomething(response: Movies.Something.Response)
    func presentFetchedMovies(response: Movies.FetchMovies.Response)
    func presentFetchError(response: Movies.Error.Response)
}

class MoviesPresenter: MoviesPresentationLogic {
    weak var viewController: MoviesDisplayLogic?
  
    // MARK: Do something
  
    func presentSomething(response: Movies.Something.Response) {
        let viewModel = Movies.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
    
    func presentFetchedMovies(response: Movies.FetchMovies.Response) {
        
        let viewModel = Movies.FetchMovies.ViewModel(movieResults: response.movieResults)
        self.viewController?.displayMovies(viewModel: viewModel)
    }
    
    func presentFetchError(response: Movies.Error.Response) {
        
    }
}
