//
//  MovieDetailModels.swift
//  DevTestArcTouch
//
//  Created by Rafael Zilião on 07/08/2018.
//  Copyright (c) 2018 Rafael Zilião. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum MovieDetail {
    // MARK: Use cases
  
    enum Something {
        struct Request {
        }
        struct Response {
        }
        struct ViewModel {
        }
    }
    
    enum FetchMovieDetails {
        struct Request {
            var movie: Movie?
        }
        struct Response {
            var movie: Movie
        }
        struct ViewModel {
            var movie: Movie
        }
    }
    
    enum ErrorFetchMovieDetais {
        struct Request {
            
        }
        struct Response {
            var message: String
        }
        struct ViewModel {
            var message: String
        }
    }

}
