//
//  MovieDetailPresenter.swift
//  DevTestArcTouch
//
//  Created by Rafael Zilião on 07/08/2018.
//  Copyright (c) 2018 Rafael Zilião. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MovieDetailPresentationLogic {
    func presentSomething(response: MovieDetail.Something.Response)
    func presentMovieDetails(response: MovieDetail.FetchMovieDetails.Response)
    func presentErrorFetchMovieDetails(response: MovieDetail.ErrorFetchMovieDetais.Response)
}

class MovieDetailPresenter: MovieDetailPresentationLogic {
    weak var viewController: MovieDetailDisplayLogic?
  
    // MARK: Do something
  
    func presentSomething(response: MovieDetail.Something.Response) {
        let viewModel = MovieDetail.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
    
    func presentMovieDetails(response: MovieDetail.FetchMovieDetails.Response) {
        let viewModel = MovieDetail.FetchMovieDetails.ViewModel(movie: response.movie)
        viewController?.displayMovieDetails(viewModel:  viewModel)
    }
    
    func presentErrorFetchMovieDetails(response: MovieDetail.ErrorFetchMovieDetais.Response) {
        
    }
}
