//
//  MovieDetailInteractor.swift
//  DevTestArcTouch
//
//  Created by Rafael Zilião on 07/08/2018.
//  Copyright (c) 2018 Rafael Zilião. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MovieDetailBusinessLogic {
    func doSomething(request: MovieDetail.Something.Request)
}

protocol MovieDetailDataStore {
  var movie: Movie! { get set }
}

class MovieDetailInteractor: MovieDetailBusinessLogic, MovieDetailDataStore {
    var presenter: MovieDetailPresentationLogic?
    var worker: MovieDetailWorker?
    var movie: Movie!
  
    // MARK: Do something
  
    func doSomething(request: MovieDetail.Something.Request) {
        worker = MovieDetailWorker()
        worker?.doSomeWork()
    
        let response = MovieDetail.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
